### ISSUE TITLE
Transpile npm modules written in ES6

### ISSUE THREAD

**Issue by kty** [babel/babel-brunch#27]
Sorry if this is a stupid question, but I can't figure out how to process npm modules written in ES6 through babel-brunch.

Right now I'm trying to use Foundation 6.2, which is written in ES2015, but babel-brunch seems to only transpile `app.js`, then concatenating Foundation's files as is.

Relevant part of `app.js`:

```javascript
import 'what-input';
import 'foundation-sites/js/foundation.core';
import 'foundation-sites/js/foundation.util.mediaQuery';
import 'foundation-sites/js/foundation.util.triggers';
import 'foundation-sites/js/foundation.util.motion';
import 'foundation-sites/js/foundation.offcanvas';

$(document).foundation();
```

I could do `import 'foundation-sites'`, which would import the precompiled ES5 file from `dist/`, but I don't want to use the huge file with all plugins included.

**Comment by es128** [comment]
@goshakkk is there currently a way to wire npm deps to run through plugins?

**Comment by goshakkk** [comment]
@es128 nope, npm deps don't get run through compilers and linters. I see how this can be desired in some cases, though; do you have an idea as to how that could work potentially? From the user perspective in the config, I mean. It's probably unwise to run all npm deps through all the plugins, so it should somehow be configured which plugins should be used for all (or should it be only whitelisted) node modules...

**Comment by es128** [comment]
I don't know. Maybe a new feature that generally allows more fine-grained control over mapping source files to plugins to address a wide variety of special cases such as this one.

Maybe expand `plugins.on` in config to something like

```js
plugins: {
  on: [{'babel-brunch': 'node_modules/foundation-sites/**/*'}]
}
```

although pulling that off may require a pretty substantial overhaul to the pipeline

**Comment by goshakkk** [comment]
I guess more fine-grained control like this would also mean more complex configs which does not go hand in hand with Brunch's mantra.

Does `{'babel-brunch': 'node_modules/foundation-sites/**/*'}` enable it **only** in that path, or that path + app code? Etc. A lot of room for confusion... 

cc @paulmillr

**Comment by paulmillr** [comment]
I'd leave this closed. If you upload things to NPM, it should always have JS equivalent.

Babel is extremely error-prone. There are many babel versions which are not compatible.

**Comment by xdave** [comment]
I'm also encountering this problem at the moment.  I'm bundling a dependency, [credit-card](https://github.com/continuationlabs/credit-card) for the browser which relies upon certain JS features that *need* to be transpiled (by _something_, anything) in order for it to work in all the browsers I'm trying to support.  It uses things like `const` and `Object.assign`, which I use babel to polyfill.

For instance, `credit-card` has one dependency [reach](https://github.com/continuationlabs/reach) that uses template strings.

These features generally are ones that are enabled by default in the recent versions of node.js, but obviously do not work in all browsers.

This is a growing trend with npm module authors because bundlers such as `browserify` and `webpack` will process these types of modules through their transform pipelines by default.

These dependencies do not come with `dist` versions.

Lots of packages are written in ES6 with the idea of modularity in mind, such as RxJS 5.  It makes it (theoretically) possible (with bundlers such as rollup) to only import the functions one needs so as not to pull in the entire package and bloat the compiled code.

To work around these problem cases, I've had to internalize these modules into my project, which is a pain, because I use [flow](http://flowtype.org/) in all of my project's modules and rely heavily on the automatic type inference it provides for stuff that's imported from `node_modules`.  However, if one imports a local module (not in `node_modules`), the type inference is not so automatic and requires you to provide _some_ type annotations -- which is what I have to do to these internalized-workaround modules.

Enabling brunch (or babel-brunch) to process, perhaps a specific set of modules contained within `node_modules` through the compilation steps, would eliminate many headaches.

**Comment by goshakkk** [comment]
https://github.com/brunch/brunch/pull/1318
